### ISSUE TITLE
Stop search adding dashes to anchor links

### ISSUE THREAD

**Issue by garethnunns** [Farrser/AvoDocs#11]
The links in the search dropdown which link to anchors (titles) within pages adds a fair few dashes to the end of the link.

For example, search for 'DMX Settings' and select the System Menu page, it links to https://avolites.fraserstockley.com/docs/system-settings/the-system-menu/#dmx-settings------
Where it should be
https://avolites.fraserstockley.com/docs/system-settings/the-system-menu/#dmx-settings

**Comment by Farrser** [comment]
Fixed 
https://github.com/Farrser/AvoDocs/commit/e4a35d188e2a5d87e123724d5d51de8fca29628e
