### ISSUE TITLE
Format Pages after DOCX -> MD conversion

### ISSUE THREAD

**Issue by garethnunns** [Farrser/AvoDocs#12]
Issue to keep track of which pages have been formatted after the port from DOCX https://github.com/Farrser/AvoDocs/commit/fee0a1f919bd2b603a13aed33cf51d3e3a9f431b

**Sections Formatted:**

- [x] **fs** ~~Introduction~~
- [x] **fs** ~~About The Consoles~~ Would be good to fix images to show correct bits of console
- [x] **fs** ~~Titan Basics~~
- [x] **fs** ~~Patching~~
- [x] **fs** ~~Controlling Fixtures~~
- [x] **gn** ~~Playback Options~~
- [x] **gn** ~~Palettes~~
- [x] **gn** ~~Effects~~
- [x] **gn** ~~Cues~~
- [x] **gn** ~~Chases~~
- [x] **gn** ~~Cue Lists~~
- [x] **gn** ~~Capture Visualiser~~
- [x] **gn** ~~Synergy~~
- [x] **gn** ~~Running The Show~~ *(could capitalise headings)*
- [x] **gn** ~~Remote Control~~
- [x] **gn** ~~Titan Net~~
- [x] **gn** ~~System Settings~~
- [x] **gn** ~~Fixture Personalities~~
- [x] **gn** ~~Networking the Console~~
- [x] **fs** ~~Titan Commands~~

**Comment by garethnunns** [comment]
Nice way to search for links in MarkDown:
`(^|[^!])\[[^\[]+\]\(.*\)`

**Comment by garethnunns** [comment]
And for finding links which aren't to .md files in VS Code:
`([^!]|^)\[[^\[]+\n*\]\([^#][a-zA-Z0-9-\.\/#]*(?<!\.md)#[a-zA-Z0-9-\.\/#]*(?<!\.md)\)`

**Comment by Farrser** [comment]
@garethnunns are all these fixed now as far as you know?

**Comment by garethnunns** [comment]
Err well #39 brings up some 404s... and could capitalise the headings?

**Comment by garethnunns** [comment]
@Farrser could close this? @congoblue has fixed many of the little bits on these pages I missed and it’s definitely MVP
