### ISSUE TITLE
Add support for videos

### ISSUE THREAD

**Issue by garethnunns** [Farrser/AvoDocs#20]
Make it simple to insert videos, looks like this will be easy in [V2](https://github.com/facebook/docusaurus/issues/1165), but for the mean time could use one of these:

- [remarkable-iframify](https://github.com/noticeableapp/remarkable-iframify#readme) looks like it just converts any link to YouTube/Vimeo/etc. into an iFrame - fairly good for future proofing
- [remarkable-youtube](https://github.com/vitaliy-bobrov/remarkable-youtube#readme) Has a few more options and documentation, but only supports YouTube and uses customised links

**Comment by Farrser** [comment]
Yeah I think it would be good to do this. Currently you can just include the iframe but for consistency, it would be good to have that done in code. The second one looks good
