### ISSUE TITLE
Remove video links from PDF

### ISSUE THREAD

**Issue by garethnunns** [Farrser/AvoDocs#43]
The easiest way to do this would be to make the links look like this in the MarkDown as they're getting completely replaced by iframify anyway:

````markdown
[](https://youtu.be/dQw4w9WgXcQ)
````

Or could make it a flag when producing the PDF and just do a regex special

Up to you @Farrser?

**Comment by Farrser** [comment]
At some point we will probably be doing an offline version for use on the consoles. We'll need to remove the videos from that as well probably
