### ISSUE TITLE
Remote Cannot Record Playbacks

### ISSUE THREAD

**Issue by KadeBehm** [Farrser/AvoDocs#61]
https://manual.avolites.com/docs/remote-control/

**Old Text (if applicable):**
You can also run and store playbacks and palettes from the remote.

Also:

Each remote has a separate programmer so an operator can continue to work on the console while another user programs other cues or palettes on the remote.

**New Text:**
You can also run and store palettes and run playbacks from the remote.

Also:
Each remote has a separate programmer so an operator can continue to work on the console while another user programs or updates palettes on the remote.

**Why it should be changed:**
the remote can not record playbacks .

**Comment by garethnunns** [comment]
Thanks for this correction, do mention any others and we'll resolve them quicker 👍
